name: Backend CD

on:
  workflow_run:
    workflows:
      - Backend CI
    branches:
      - main
    types: 
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    name: Build Deploy
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Get Dependencies
      run: go mod tidy
      working-directory: ./api

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o ./main ./main.go
      working-directory: ./api

    - name: Zip
      run: zip function.zip main
      working-directory: ./api

    - name: Deploy
      uses: appleboy/lambda-action@master
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: go-sample-function
          zip_file: ./api/function.zip
