name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FILE_PATTERN: "'src/**/*.{js}'"

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.15.0
          cache: npm
      - name: Clean Install Dependencies
        run: npm ci
        working-directory: ./web
      - name: Run ESLint
        run: nom run lint
        working-directory: ./web

  prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.15.0
          cache: npm
      - name: Clean Install Dependencies
        run: npm ci
        working-directory: ./web
      - name: Run Prettier
        run: node_modules/.bin/prettier ${FILE_PATTERN}
        working-directory: ./web

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.15.0
          cache: npm
      - name: Clean Install Dependencies
        run: npm ci
        working-directory: ./web
      - name: Run Test
        run: npm run test
        working-directory: ./web



