name: Frontend CD

on:
  workflows: ["Frontend CI"]
  branches: [ main ]
  types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean Install Dependencies
        run: npm install
        working-directory: ./web

      - name: Build
        run: npm run build
        working-directory: ./web

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 cp --recursive --region ap-northeast-1 build s3://react-static-website-hosting
        working-directory: ./web
